### ISSUE TITLE
No Sea Animals On Land

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [ProjectFairnessLabs/PF-vMenu#9]
By default, being able to select animal ped models is disabled in vMenu, the menu precisely states that it may cause issues or an indefinite death trap; the reason behind this is due to the fact sea creatures on land causes you to die, respawn, and die again in an indefinite loop. 

What I suggested, is that it detects if you're a certain model and IsPedInWater or I believe IsPedSwimming natives, and if false, don't allow the sea creatures to be spawned - also print in chat warning people why it won't work for them.

**Comment by tristencommunity** [comment]
Believe that this is already a thing. If the only reason why the animal ped models are disabled due to that bug, I believe it could now be re-enabled since Vespura fixed this awhile back ago (https://github.com/TomGrobbe/vMenu/blob/f44846414ac4dedc18ecce7cebc708f5ab161832/vMenu/menus/PlayerAppearance.cs#LL427C1-L427C1).

https://github.com/ProjectFairnessLabs/PF-vMenu/blob/47ff0d3c8ee0f74e8632177d1c9625f17a639afc/vMenu/menus/PlayerAppearance.cs#L427
